### ISSUE TITLE
Version 1.3.0 UglifyJs Error

### ISSUE THREAD

**Issue by Dima000** [egeriis/zipcelx#23]
Hello,

We run a webpack minifier on vendor folder and we run into an error since you released version 1.3.0.
The error is the terminal is the following:

```
ERROR in [filename.js] from UglifyJs  
Unexpected token: operator (>) [filename.js:[location]
```

In the minified file the error is around
```
....
var oh=e=>e.filename?"string"!=typeof e.filename?(console.error("Zipclex filename can only be of type string"),!1):Array.isArray(e.sheet.data) 
....
```

When downgraded to version 1.2.0 all works fine. Hope it is of use.

###### Other packages versions:
```
zipcelx: version "1.3.0"
web-pack-plugin: version "2.30.1"
html-minifier: "3.5.10"
uglify-js: version "3.3.13"
```

**Comment by egeriis** [comment]
This is likely the same issue as #24. Since you're not using uglify-es, you have to use the ES5 build, which is found in `lib/bundle.js`, where as you're probably using `lib/module.js`. It's highly likely that this is a fault on our part though, as the `lib/module.js` build apparently cannot contain other ES6 features than _modules_.
